### ISSUE TITLE
"OpenCV: terminate handler is called" when ripping Crown-Splitter

### ISSUE THREAD

**Issue by McCaffeteria** [MontagueM/MontevenDynamicExtractor#4]
As the title says, I'm getting an error when I try to rip the Crown-Splitter sword in MDE v1.6.1. I'm not aware of any other items that won't extract, seems to only be this sword. The issue also exists in MDE v1.6.0, but the issue does not exist in MDE v1.5.0.

Here is the output from the failed v1.6.1 extraction:

> F:\Destiny Model Rips\Monteven Dynamic Extractor\MDE v1.6.1>MontevenDynamicExtractorv1.6.1 -p "D:/Steam/steamapps/common/Destiny 2/packages" -o "F:/Destiny Model Rips/Destiny 2 MDE Extractions/Temp" -a 2782325302 -t -s 2
> API flag found, getting api models...
> exporting api model...
> 
> Dynamic has no mesh data (C), skipping...Skeleton flag 2, ripped models will use the player face rig.
> 
> File extraction readied...
> texconv.exe "F:/Destiny Model Rips/Destiny 2 MDE Extractions/Temp/2782325302//textures/f64bac80.dds" -y -ft png -f BC1_UNORM_SRGBMicrosoft (R) DirectX Texture Converter [DirectXTex] Version 2021.1.10.2
> Copyright (C) Microsoft Corp. All rights reserved.
> 
> reading F:/Destiny Model Rips/Destiny 2 MDE Extractions/Temp/2782325302//textures/f64bac80.dds (1024x2048 BC1_UNORM_SRGB 2D) as (1024x2048 R8G8B8A8_UNORM_SRGB 2D α:Opaque)
> writing F:/Destiny Model Rips/Destiny 2 MDE Extractions/Temp/2782325302//textures/f64bac80.PNG
> OpenCV: terminate handler is called! The last OpenCV error is:
> OpenCV(4.5.2) Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in cv::Mat::Mat, file C:\build\master_winpack-build-win64-vc15\opencv\modules\core\src\matrix.cpp, line 811
> 
> F:\Destiny Model Rips\Monteven Dynamic Extractor\MDE v1.6.1>pause
> Press any key to continue . . .

**Comment by MontagueM** [comment]
Fix is in the works, projection likely June
